### ISSUE TITLE
Pager issues on OS X

### ISSUE THREAD

**Issue by superfunc** [aitjcize/cppman#56] opened 2016-01-16 23:13 UTC
When trying to double click, or press enter, on a function name in the page. The following error message is displayed in the vim buffer.

Error Message:
error: [Errno 19] Operation not supported by device.

Relevant Software Versions:
- usr/local/bin/cppman Ver 0.4.6
- NVIM 0.1.1 (compiled Dec 27 2015 16:32:11)

**Comment by eborisch** [comment] 2016-02-15 22:06
The issue is with the `ws = fcntl.ioctl(0, termios.TIOCGWINSZ, ws)` line in cppman/util.py -- when cppman is re-run (which is what is happening) by vim on OS X, this is returning ENODEV.

Placing this line (and the next) in a try.. except.. and returning some dummy values: `lines, columns, x, y = (24, 80, 0, 0)` in the except... is enough to get it working, but I haven't looked for unintended consequences...

**Comment by aitjcize** [comment] 2016-02-16 01:14
I think there is an alternative for TIOCGWSINZ on OS X, I'll look into it.

**Comment by eborisch** [comment] 2016-02-16 05:37
Perhaps calling 'tput cols' would be an alternative? I haven't tried it here to see how it reacts in this particular situation.

**Comment by eborisch** [comment] 2016-02-19 04:56
I've added a cppman port to MacPorts, including this patch which appears to resolve (was broken, now fixed for me) this issue:
https://trac.macports.org/browser/trunk/dports/lang/cppman/files/cppman_util_py.patch?rev=145849

**Comment by aitjcize** [comment] 2016-02-19 07:56
Yeah that works. Let me include this patch.

**Comment by aitjcize** [comment] 2016-02-19 08:32
I've send 5cd2e74 to fix this issue. I don't use 'tput' to avoid the external dependency.

**Closed by aitjcize** 2016-02-19 08:32 UTC
Labels: Started

**Comment by aitjcize** [comment] 2016-02-19 08:38
Thanks for maintaining the MacPort package btw!

**Comment by superfunc** [comment] 2016-02-23 07:53
Thanks to everyone for working on this!
