### ISSUE TITLE
No manual entry for anything

### ISSUE THREAD

**Issue by jim3** [aitjcize/cppman#158] opened 2023-06-11 18:45 UTC
I installed the cppman package via apt. 

When trying to access the docs at cplusplus.com it is giving me: 
`No manual entry for` anything I give it. 

For example:
`cppman vector::begin` gives me `No manual entry for vector::begin`

Also, if I try to switch to cppreference I get an HTTP error:

`cppman -s cppreference.com` gives me: `error: HTTP Error 403: Forbidden`

`uname -a` is:
```bash
Linux host1 6.1.0-kali9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1kali1 (2023-05-12) x86_64 GNU/Linux
```

**Comment by aitjcize** [comment] 2023-06-12 02:44
@jim3 the issue is fixed in the latest version 0.5.6. The package hasn't yet been updated upstream. Please install cppman with `pip install cppman` for the time being.

**Closed by aitjcize** 2023-06-12 02:44 UTC
